
DROP TABLE IF EXISTS postuler;
DROP TABLE IF EXISTS stages;
DROP TABLE IF EXISTS contacter;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS professionnels;
DROP TABLE IF EXISTS pannes;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS materiels;
DROP TABLE IF EXISTS utilisateurs;
